--Exercício 2
CREATE TABLE Nutricionista (
	ID_NUTRICIONISTA SERIAL  PRIMARY KEY,
	CRN VARCHAR(50) NOT NULL,
	ESPECIALIDADE VARCHAR(50) NOT NULL,
	TEMPO_EXPERIENCIA INTEGER NOT NULL
);

CREATE TABLE Paciente (
	ID_PACIENTE SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CPF VARCHAR(15) NOT NULL,
	TELEFONE VARCHAR(16),
	EMAIL VARCHAR(50)
);

CREATE TABLE Consulta (
	ID_CONSULTA SERIAL PRIMARY KEY,
	ID_PACIENTE INTEGER REFERENCES Nutricionista(ID_NUTRICIONISTA),
	ID_NUTRICIONISTA INTEGER REFERENCES Paciente(ID_PACIENTE),
	DATA_CONSULTA DATE NOT NULL,
	OBSERVACOES VARCHAR(200),
	UNIQUE(ID_NUTRICIONISTA, ID_PACIENTE)
);

DROP TABLE Nutricionista;
DROP TABLE Paciente;
DROP TABLE Consulta;

--Exercício 3

INSERT INTO Nutricionista (CRN, ESPECIALIDADE, TEMPO_EXPERIENCIA)
	VALUES ('CRN-5/ 1111/P', 'ESPORTES', 5);

INSERT INTO Paciente (NOME, DATA_NASCIMENTO, CPF, TELEFONE, EMAIL)
	VALUES('Teste Silva', '01-01-1999', '111.111.111-11', '(48) 9 9999-9999', 'teste@hotmail.com');

INSERT INTO Consulta (ID_NUTRICIONISTA, ID_PACIENTE, DATA_CONSULTA, OBSERVACOES)
	VALUES (1, 1, '01-01-2024', 'Paciente melhorou seu desempenho no esporte');