--Exercício 2
CREATE TABLE Nutricionista (
	ID_NUTRICIONISTA SERIAL  PRIMARY KEY,
	CRN VARCHAR(50) NOT NULL,
	ESPECIALIDADE VARCHAR(50) NOT NULL,
	TEMPO_EXPERIENCIA INTEGER NOT NULL
);

CREATE TABLE Paciente (
	ID_PACIENTE SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CPF VARCHAR(15) NOT NULL,
	TELEFONE VARCHAR(16),
	EMAIL VARCHAR(50)
);

CREATE TABLE Consulta (
	ID_CONSULTA SERIAL PRIMARY KEY,
	ID_PACIENTE INTEGER REFERENCES Nutricionista(ID_NUTRICIONISTA),
	ID_NUTRICIONISTA INTEGER REFERENCES Paciente(ID_PACIENTE),
	DATA_CONSULTA DATE NOT NULL,
	OBSERVACOES VARCHAR(200),
	UNIQUE(ID_NUTRICIONISTA, ID_PACIENTE)
);

DROP TABLE Nutricionista;
DROP TABLE Paciente;
DROP TABLE Consulta;